_wandb:
    value:
        cli_version: 0.23.0
        e:
            dyjn8d0eokevk4gktgp0o6l043is45u6:
                codePath: myosuite/MME/main.py
                codePathLocal: main.py
                email: zst806038347@gmail.com
                executable: /home/jz7785/miniconda3/envs/myosuite/bin/python
                git:
                    commit: fdb79f74bf916a51f8c2a15d66c0b1b8c3056a0c
                    remote: https://github.com/Iverson0630/myoEXO.git
                host: ENG-HS5894-UBUNTU
                os: Linux-6.14.0-24-generic-x86_64-with-glibc2.39
                program: /home/jz7785/ZST/myoEXO/myosuite/MME/main.py
                python: CPython 3.11.0
                root: /home/jz7785/ZST/myoEXO/myosuite/MME
                startedAt: "2025-11-12T00:09:35.333040Z"
                writerId: dyjn8d0eokevk4gktgp0o6l043is45u6
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.11.0
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
